### ISSUE TITLE
Improve support to tab completion

### ISSUE THREAD

**Issue by patito** [NeowayLabs/nash#58]
Tab completion is extremely helpful in command line environment I think nash could improve this feature.

**Comment by tiago4orion** [comment]
I'm working on it. 

After lose the fight against readline lib I decided to drop built-in support for autocomplete and add a hook to users do their own autocomplete using nash scripts and third party libs.

The benefit is that nash interactive cli is now much more simple. The problem is that a fresh install of nash will have no autocomplete at all.

https://asciinema.org/a/760o67f6s7kjrj1f4o54d882v?autoplay=true

I'll make a PR soon.

**Comment by patito** [comment]
showwwwwww

**Comment by ryukinix** [comment]
@tiago4orion how can I use that?

**Comment by katcipis** [comment]
@ryukinix I think you just have to install nashcomplete.

https://github.com/katcipis/dotnash/blob/master/Makefile#L7
